In [1]:
! git clone https://github.com/yifan-zhou19/Policy_migration.git migration

Cloning into 'migration'...
remote: Enumerating objects: 114, done.
remote: Total 114 (delta 0), reused 0 (delta 0), pack-reused 114
Receiving objects: 100% (114/114), 1.33 MiB | 13.09 MiB/s, done.
Resolving deltas: 100% (64/64), done.


In [2]:
! ls migration/

'100 50 10 10 50 1 4'	 'Data3 200 50 10 10 100 1 4'   Uni_matrix.ipynb
'50 50 10 10 50 1 4'	 'Data 50 50 50 50 50 1 4'      Video_matrix.ipynb
'8 8 10 10 10 1 1'	  Migration_evaluation.ipynb
'Data2 200 50 10 10 10'   README.md


In [70]:
# generate user
#file = open(r'migration/Data3 200 50 10 10 100 1 4/policy.txt' , 'r')
#file = open(r'migration/Data2 200 50 10 10 10/policy.txt' , 'r')
file = open(r'migration/8 8 10 10 10 1 1/policy.txt' , 'r')
line = file.readline() 
RU=[]      
while line: 
  rule=dict()
  rule['expressions']=[{'eu':{},'er':{}}]
  rule['operations']=['access']
  rule['decision']='allow'
 # rule=dict('expressions':[{'eu':{},'er':{}}],'operations':['access'],'decision':'allow'), 
  
  #print(line[:10])
  #print(line, end = '')　
  cons = line.strip().split(',')
  for con in cons:
    c = con.split('=')
    if c[0][0]=='u':
      rule['expressions'][0]['eu'][c[0]]=[('is',c[1])]
    elif c[0][0]=='r':
      #rule['er'][c[0]]=c[1]
      rule['expressions'][0]['er'][c[0]]=[('is',c[1])]

  
  RU.append(rule)

  #break
  line = file.readline() 
print(len(RU))
for i in RU:
  print(i)
 
file.close() 

10
{'expressions': [{'eu': {'uattrib3': [('is', '{3a}')], 'uattrib9': [('is', '{9a}')], 'uattrib4': [('is', '{4a}')]}, 'er': {'rattrib7': [('is', '{7w}')], 'rattrib8': [('is', '{8w}')], 'rattrib2': [('is', '{2w}')], 'rattrib4': [('is', '{4w}')], 'rattrib6': [('is', '{6w}')], 'rattrib3': [('is', '{3w}')]}}], 'operations': ['access'], 'decision': 'allow'}
{'expressions': [{'eu': {'uattrib6': [('is', '{6a}')], 'uattrib1': [('is', '{1a}')], 'uattrib9': [('is', '{9a}')], 'uattrib3': [('is', '{3a}')]}, 'er': {'rattrib7': [('is', '{7w}')], 'rattrib9': [('is', '{9w}')], 'rattrib5': [('is', '{5w}')]}}], 'operations': ['access'], 'decision': 'allow'}
{'expressions': [{'eu': {'uattrib8': [('is', '{8a}')], 'uattrib7': [('is', '{7a}')], 'uattrib4': [('is', '{4a}')], 'uattrib9': [('is', '{9a}')], 'uattrib1': [('is', '{1a}')], 'uattrib5': [('is', '{5a}')]}, 'er': {'rattrib1': [('is', '{1w}')], 'rattrib5': [('is', '{5w}')]}}], 'operations': ['access'], 'decision': 'allow'}
{'expressions': [{'eu': {'ua

In [71]:
file = open(r'migration/8 8 10 10 10 1 1/UAR.txt' , 'r')
line = file.readline()
U=[] 
UA=[] 
i=1 
while line: 
  u={}
  #print(line[:10])
  #print(line, end = '')　
  cons = line.strip().split(',')
  for con in cons:
    c = con.split('=')
    if(len(c)==2):
      u[c[0]]=c[1]
      if(c[0] not in UA):
        UA.append(c[0])
  u['uid']='user'+str(i)
  i=i+1

  
  U.append(u)

  #break
  line = file.readline() 
print(len(U))
for i in U:
  print(i)
 
print(UA)
file.close() 

8
{'uattrib2': '{2a}', 'uattrib3': '{3a}', 'uattrib4': '{4a}', 'uattrib7': '{7a}', 'uattrib8': '{8a}', 'uattrib9': '{9a}', 'uid': 'user1'}
{'uattrib0': '{0a}', 'uattrib1': '{1a}', 'uattrib2': '{2a}', 'uattrib3': '{3a}', 'uattrib6': '{6a}', 'uattrib8': '{8a}', 'uattrib9': '{9a}', 'uid': 'user2'}
{'uattrib1': '{1a}', 'uattrib2': '{2a}', 'uattrib4': '{4a}', 'uattrib5': '{5a}', 'uattrib6': '{6a}', 'uattrib7': '{7a}', 'uattrib8': '{8a}', 'uattrib9': '{9a}', 'uid': 'user3'}
{'uattrib1': '{1a}', 'uattrib5': '{5a}', 'uattrib6': '{6a}', 'uattrib7': '{7a}', 'uattrib9': '{9a}', 'uid': 'user4'}
{'uattrib0': '{0a}', 'uattrib1': '{1a}', 'uattrib2': '{2a}', 'uattrib3': '{3a}', 'uattrib4': '{4a}', 'uattrib5': '{5a}', 'uattrib6': '{6a}', 'uattrib7': '{7a}', 'uattrib8': '{8a}', 'uattrib9': '{9a}', 'uid': 'user5'}
{'uattrib0': '{0a}', 'uattrib1': '{1a}', 'uattrib2': '{2a}', 'uattrib3': '{3a}', 'uattrib4': '{4a}', 'uattrib5': '{5a}', 'uattrib6': '{6a}', 'uattrib7': '{7a}', 'uattrib8': '{8a}', 'uattrib9': 

In [72]:
file = open(r'migration/8 8 10 10 10 1 1/OAR.txt' , 'r')
line = file.readline()
R=[] 
RA=[]
i=1     
while line: 
  r={}
  #print(line[:10])
  #print(line, end = '')　
  cons = line.strip().split(',')
  for con in cons:
    c = con.split('=')
    if(len(c)==2):
      r[c[0]]=c[1]
      if(c[0] not in RA):
        RA.append(c[0])

  r['rid']='resource'+str(i)
  i=i+1
  R.append(r)

  #break
  line = file.readline() 
print(len(R))
for i in R:
  print(i)
 
print(RA)
file.close() 

8
{'rattrib0': '{0w}', 'rattrib2': '{2w}', 'rattrib3': '{3w}', 'rattrib4': '{4w}', 'rattrib6': '{6w}', 'rattrib7': '{7w}', 'rattrib8': '{8w}', 'rattrib9': '{9w}', 'rid': 'resource1'}
{'rattrib0': '{0w}', 'rattrib3': '{3w}', 'rattrib5': '{5w}', 'rattrib7': '{7w}', 'rattrib8': '{8w}', 'rattrib9': '{9w}', 'rid': 'resource2'}
{'rattrib1': '{1w}', 'rattrib4': '{4w}', 'rattrib5': '{5w}', 'rattrib6': '{6w}', 'rattrib7': '{7w}', 'rid': 'resource3'}
{'rattrib0': '{0w}', 'rattrib1': '{1w}', 'rattrib3': '{3w}', 'rattrib4': '{4w}', 'rattrib5': '{5w}', 'rattrib6': '{6w}', 'rattrib7': '{7w}', 'rattrib8': '{8w}', 'rattrib9': '{9w}', 'rid': 'resource4'}
{'rattrib0': '{0w}', 'rattrib2': '{2w}', 'rattrib3': '{3w}', 'rattrib4': '{4w}', 'rattrib5': '{5w}', 'rattrib6': '{6w}', 'rattrib7': '{7w}', 'rattrib8': '{8w}', 'rattrib9': '{9w}', 'rid': 'resource5'}
{'rattrib0': '{0w}', 'rattrib1': '{1w}', 'rattrib2': '{2w}', 'rattrib3': '{3w}', 'rattrib4': '{4w}', 'rattrib5': '{5w}', 'rattrib6': '{6w}', 'rattrib7': 

In [73]:
O=['access']
def dU(user,attribute):
  if attribute in user.keys():
    return user[attribute]

def dR(resource,attribute):
  if attribute in resource.keys():
    return resource[attribute]
ABAC_policy=(U,R,O,UA,RA,dU,dR,RU)

In [74]:
def satisfied(u,r,expressions):
  for expression in expressions:
    eu=expression['eu']
    er=expression['er']
    #for all the keys in eu get the constrina of this key
    #if u does not satisfy this const return false\
    if ( len(eu.keys()) != 0 and u != None):
      for key in eu.keys():
        for (op,c) in eu[key]:
          if dU(u,key)==None:
            return False
          if op == 'is':
            if dU(u,key) != c and dU(u,key) != None:
              return False

    #for all the keys in er get the constrinat of the key
    if ( len(er.keys()) != 0 and r!=None):
      for key in er.keys():
        for (op,c) in er[key]:
        #print(op,c)
        #op,c=er[key]
          if(dR(r,key)==None):
          #  print(dR(r,key),key,op,c)
            return False
          if op == 'is':

            if dR(r,key)!=c  and dR(r,key) != None:
             # print(dR(r,key),c)
              return False
  
  return True


def check_ABAC_policy(request,abac_policy):
  u,r,o =request
  _,_,_,_,_,_,_,rules = abac_policy
  for rule in rules:
    if o in rule['operations']:
      if satisfied(u,r,rule['expressions']):
        return True
  return False

# check the ABAC policy 
number_allow=0
number_deny=0
for u in U:
  for r in R:
    for o in O:
      if(check_ABAC_policy((u,r,o),ABAC_policy)==True):
        #print(u,'\n',r)
        number_allow= number_allow+1
      else:
        number_deny =number_deny +1 
        #print(f'{u}\n{r}\n{o}\n \n')

print(f'For ABAC policy:\nNumber of allow:{number_allow}\nNumber of deny:{number_deny}')

#print(f'{check_ABAC_policy((U[6],R[7],"readMyScores"),ABAC_university)}\n{U[6]}\n{R[7]}')
#print(f'{check_ABAC_policy((U[3],R[5],"addScore"),ABAC_university)}\n{U[3]}\n{R[5]}')
#print(f'Loss at epo {epoch}: {losses/len(training_data)}')



For ABAC policy:
Number of allow:48
Number of deny:16


In [81]:
def get_item_id(item,list):
  id = 0
  while(id<len(list)):
    if item == list[id]:
      return id
    id = id + 1
  return None

from numpy import *
# Calculate the number of user constraints
# Calculate the number of permissions(resource constraint,operation)
UC=[]
Permission=[]
Permission_set=[]
EU=[]
for rule in RU:
  user_cons=rule['expressions'][0]['eu']
  resource_cons=rule['expressions'][0]['er']
  #print(user_cons)
  #print(resource_cons)
  operations=rule['operations']
  for uc_key in user_cons.keys():
    uc = {uc_key:user_cons[uc_key]}
    if uc not in UC:
      UC.append(uc)
  if (resource_cons,operations) not in Permission:
    Permission.append((resource_cons,operations))
  if user_cons not in EU:
    EU.append(user_cons)
    Permission_set.append([resource_cons,operations])
  else:
    Permission_set[get_item_id(user_cons,EU)].append((resource_cons,operations))
n_uc=len(UC)
#n_p=len(Permission_set)
n_p=len(Permission)
print(f'Number of user constraints:{n_uc}\nNumber of Permission sets:{n_p}')
#print(UC)
#print(Permission)

Number of user constraints:10
Number of Permission sets:8


In [82]:
def get_item_id(item,list):
  id = 0
  while(id<len(list)):
    if item == list[id]:
      return id
    id = id + 1
  return None

def cover(ma,mb):# ma cover mb
  if ma.shape[1] != mb.shape[1]:
    return False
  for i in range(ma.shape[1]):
    if mb[0,i]==1 and ma[0,i]==0:
      return False


  return True

In [83]:
# permission-constraint matrix
pc=mat(zeros((n_p,n_uc)))
for rule in RU:
  user_cons=rule['expressions'][0]['eu']
  resource_cons=rule['expressions'][0]['er']
  operations=rule['operations']
  p_id=get_item_id((resource_cons,operations),Permission)
  for uc_key in user_cons.keys():
    uc = {uc_key:user_cons[uc_key]}
    c_id=get_item_id(uc,UC)
    if(c_id==None):
      continue
    pc[p_id,c_id]=1
print(f'The pc matrix is\n {pc}')
rp=mat(diag(array(ones(n_p))))
for i in range(n_p-1):
  for j in range(i+1,n_p):
    if (cover(pc[i,],pc[j,])):
      rp[i,j]=1
    if (cover(pc[j,],pc[i,])):
      rp[j,i]=1

print(f'The rp matrix is\n {rp}')

The pc matrix is
 [[1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [1. 0. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 0. 1. 0. 0. 1. 1. 0.]]
The rp matrix is
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1.]]


In [84]:
def rest_of(l,r):
  vector = mat(zeros((1,n_uc)))
  for role in l:
    if role != r:
      vector = vector + rc[role,]
  for i in range(n_uc):
    if vector[0,i]>0:
      vector[0,i]=1
  return vector
num_ur=0;
num_rp=0
import copy
# User role assignment 
n_r=n_p
rc=pc
URA = dict()
for u in U:
  URA[u['uid']]=[]
  uv=mat(ones((1,n_uc)))
  for cid in range(n_uc):
    expressions=[{'eu':UC[cid],'er':{}}]
    if satisfied(u,None,expressions)==False:
      uv[0,cid]=0
  for rid in range(n_r):
    if cover(uv,rc[rid,]):
      URA[u['uid']].append(rid)

# remove hierarchy
  for ri in URA[u['uid']]:
    rest = URA[u['uid']].copy()
    rest.remove(ri)

    for rj in rest:
      if cover(rc[rj,],rc[ri,]) and ri in URA[u['uid']]:
        URA[u['uid']].remove(ri)
#remove redundant
  for r in URA[u['uid']]:
    if len(URA[u['uid']])==1:
      break
    if cover(rest_of(URA[u['uid']],r),rc[r,]):
      URA[u['uid']].remove(r)

  ura =  URA[u['uid']]
  num_ur=num_ur+len(ura)

  print(f'User {u}, role: {ura}')
#print(f'The user-role assignment:  {URA}')
 # print(f'The role-permission assignment:  {RPA}')

# generate the role-heirarchy
RH = []
for i in range(0,n_r-1):
  for j in range(i+1,n_r):
    if (cover(pc[i,],pc[j,])):
      RH.append((i,j))
    if (cover(pc[j,],pc[i,])):
      RH.append((j,i))    
print(f'The role-hierarchy relationship:  {RH}')
# generate the role-permission assignment
RPA = dict()
for ro in range(n_r):
  RPA['role'+str(ro)]=[]
  for r in R:
    for o in O:
      for pid in range(n_p):
        if rp[ro,pid]==1:
          (er,operations) = Permission[pid]
          #print(er,r)
          expressions=[{'eu':{},'er':er}]
          #print(satisfied(None,r,expressions))
          if satisfied(None,r,expressions) and o in operations:
            if((r,o) not in RPA['role'+str(ro)]):
              RPA['role'+str(ro)].append((r,o))


for ro in range(n_r):
  p=RPA['role'+str(ro)]
  num_rp=num_rp+len(p)
  print(f'Role：{ro}, Number:{len(p)},  Permissions: {p}')

print(f'Number of user-role assignment:{num_ur},Number of role-permission assignment:{num_rp}')

User {'uattrib2': '{2a}', 'uattrib3': '{3a}', 'uattrib4': '{4a}', 'uattrib7': '{7a}', 'uattrib8': '{8a}', 'uattrib9': '{9a}', 'uid': 'user1'}, role: [0]
User {'uattrib0': '{0a}', 'uattrib1': '{1a}', 'uattrib2': '{2a}', 'uattrib3': '{3a}', 'uattrib6': '{6a}', 'uattrib8': '{8a}', 'uattrib9': '{9a}', 'uid': 'user2'}, role: [1]
User {'uattrib1': '{1a}', 'uattrib2': '{2a}', 'uattrib4': '{4a}', 'uattrib5': '{5a}', 'uattrib6': '{6a}', 'uattrib7': '{7a}', 'uattrib8': '{8a}', 'uattrib9': '{9a}', 'uid': 'user3'}, role: [2, 3]
User {'uattrib1': '{1a}', 'uattrib5': '{5a}', 'uattrib6': '{6a}', 'uattrib7': '{7a}', 'uattrib9': '{9a}', 'uid': 'user4'}, role: [3]
User {'uattrib0': '{0a}', 'uattrib1': '{1a}', 'uattrib2': '{2a}', 'uattrib3': '{3a}', 'uattrib4': '{4a}', 'uattrib5': '{5a}', 'uattrib6': '{6a}', 'uattrib7': '{7a}', 'uattrib8': '{8a}', 'uattrib9': '{9a}', 'uid': 'user5'}, role: [3, 5]
User {'uattrib0': '{0a}', 'uattrib1': '{1a}', 'uattrib2': '{2a}', 'uattrib3': '{3a}', 'uattrib4': '{4a}', 'ua

In [85]:
# check RBAC policy
def check_RBAC_policy(request,rp,URA):
  u,r,o =request
  for role_id in URA[u['uid']]:
    for pid in range(n_p):
      if rp[role_id,pid]==1:
        (er,operations) = Permission[pid]
        expressions=[{'eu':{},'er':er}]
        if satisfied(u,r,expressions) and o in operations:
          return True


  return False
# Check the RBAC
# check the RBAC policy 

number_allow=0
number_deny=0
for u in U:
  for r in R:
    for o in O:
      if(check_RBAC_policy((u,r,o),rp,URA)==True):
        number_allow= number_allow+1
      else:
        number_deny =number_deny +1 
        #print(f'{u}\n{r}\n{o}\n \n')

print(f'For RBAC:\nNumber of allow:{number_allow}\nNumber of deny:{number_deny}')

For RBAC:
Number of allow:48
Number of deny:16


In [86]:

# check the RBAC policy 
number_allow=0
number_deny=0
for u in U:
  for r in R:
    for o in O:
      if(check_RBAC_policy((u,r,o),rp,URA)==True):
        number_allow= number_allow+1
      else:
        number_deny =number_deny +1 
        #print(f'{u}\n{r}\n{o}\n \n')

print(f'For RBAC:\nNumber of allow:{number_allow}\nNumber of deny:{number_deny}')

# check the ABAC policy 
number_allow=0
number_deny=0
m= []
for u in U:
  l = []
  for r in R:
    for o in O:
      if(check_ABAC_policy((u,r,o),ABAC_policy)==True):
        l.append(1)
        number_allow= number_allow+1
      else:
        number_deny =number_deny +1 
        l.append(0)
        #print(f'{u}\n{r}\n{o}\n \n')
  m.append(l)

print(f'For ABAC:\nNumber of allow:{number_allow}\nNumber of deny:{number_deny}')
#for i in m:
#  print(i)
#number_allow=0
#number_deny=0

correct=0
for u in U:
 
  for r in R:
    for o in O:
      if (check_ABAC_policy((u,r,o),ABAC_policy)==True and check_RBAC_policy((u,r,o),rp,URA)==False):
        print(f'TF{u} {r} {o}')
      elif (check_ABAC_policy((u,r,o),ABAC_policy)==False and check_RBAC_policy((u,r,o),rp,URA)==True):
        print(f'FT{u} {r} {o}')
        #number_allow= number_allow+1
      elif (check_ABAC_policy((u,r,o),ABAC_policy)==True and check_RBAC_policy((u,r,o),rp,URA)==True):
        correct = correct +1
      elif (check_ABAC_policy((u,r,o),ABAC_policy)==False and check_RBAC_policy((u,r,o),rp,URA)==False):
        correct = correct +1
        #number_deny =number_deny +1 
        #print(f'{u}\n{r}\n{o}\n \n')

print(f'For number of correct:{correct}')


For RBAC:
Number of allow:48
Number of deny:16
For ABAC:
Number of allow:48
Number of deny:16
For number of correct:64
