<a href="https://colab.research.google.com/github/yifan-zhou19/Policy_migration/blob/master/Migration_evaluation(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Policy migration using randomly generated datasets

## Preparing the datasets

In [3]:
! git clone https://github.com/yifan-zhou19/Policy_migration.git migration

fatal: destination path 'migration' already exists and is not an empty directory.


In [4]:
! ls migration/

'100 50 10 10 50 1 4'		       'Data3 200 50 10 10 100 1 4'
'50 50 10 10 40 1 4'		       'Data 50 50 50 50 50 1 4'
'[50 50 10 10 40 1 4]10  (16)'	       'Migration_evaluation(2).ipynb'
'[50 50 10 10 40 1 4] 50(34)'	       'Migration_evaluation(3).ipynb'
'[50 50 10 10 40 1 4] last 20 (6)'      Migration_evaluation.ipynb
'[50 50 10 10 40 1 4] middle 20 (25)'   README.md
'50 50 10 10 50 1 4'		        Uni_matrix.ipynb
'8 8 10 10 10 1 1'		        Video_matrix.ipynb
'Data2 200 50 10 10 10'


## Extract policies

In [26]:

#file = open(r'migration/8 8 10 10 10 1 1/policy.txt' , 'r')
file = open(r'migration/50 50 10 10 50 1 4/policy.txt' , 'r')
line = file.readline() 
RU=[]      
while line: 
  rule=dict()
  rule['expressions']=[{'eu':{},'er':{}}]
  rule['operations']=['access']
  rule['decision']='allow'
 # rule=dict('expressions':[{'eu':{},'er':{}}],'operations':['access'],'decision':'allow'), 
  
  #print(line[:10])
  #print(line, end = '')　
  cons = line.strip().split(',')
  for con in cons:
    c = con.split('=')
    if c[0][0]=='u':
      rule['expressions'][0]['eu'][c[0]]=[('is',c[1])]
    elif c[0][0]=='r':
      #rule['er'][c[0]]=c[1]
      rule['expressions'][0]['er'][c[0]]=[('is',c[1])]

  
  RU.append(rule)

  #break
  line = file.readline() 
print(f'Number of policies:{len(RU)}')
for i in RU:
  print(i)
 
file.close() 

Number of policies:50
{'expressions': [{'eu': {'uattrib3': [('is', '{3a}')], 'uattrib9': [('is', '{9b}')], 'uattrib4': [('is', '{4c}')]}, 'er': {'rattrib7': [('is', '{7w}')], 'rattrib8': [('is', '{8w}')], 'rattrib2': [('is', '{2x}')], 'rattrib4': [('is', '{4w}')], 'rattrib6': [('is', '{6x}')], 'rattrib3': [('is', '{3w}')]}}], 'operations': ['access'], 'decision': 'allow'}
{'expressions': [{'eu': {'uattrib6': [('is', '{6a}')], 'uattrib1': [('is', '{1d}')], 'uattrib9': [('is', '{9c}')], 'uattrib3': [('is', '{3a}')]}, 'er': {'rattrib7': [('is', '{7w}')], 'rattrib9': [('is', '{9w}')], 'rattrib5': [('is', '{5y}')]}}], 'operations': ['access'], 'decision': 'allow'}
{'expressions': [{'eu': {'uattrib8': [('is', '{8a}')], 'uattrib7': [('is', '{7b}')], 'uattrib4': [('is', '{4d}')], 'uattrib9': [('is', '{9b}')], 'uattrib1': [('is', '{1c}')], 'uattrib5': [('is', '{5d}')]}, 'er': {'rattrib1': [('is', '{1z}')], 'rattrib5': [('is', '{5y}')]}}], 'operations': ['access'], 'decision': 'allow'}
{'express

## Extract users

In [27]:
#file = open(r'migration/8 8 10 10 10 1 1/UAR.txt' , 'r')
file = open(r'migration/50 50 10 10 50 1 4/UAR.txt' , 'r')
line = file.readline()
U=[] 
UA=[] 
i=1 
while line: 
  u={}
  #print(line[:10])
  #print(line, end = '')　
  cons = line.strip().split(',')
  for con in cons:
    c = con.split('=')
    if(len(c)==2):
      u[c[0]]=c[1]
      if(c[0] not in UA):
        UA.append(c[0])
  u['uid']='user'+str(i)
  i=i+1

  
  U.append(u)

  #break
  line = file.readline() 
print(f'Number of users:{len(U)}')
for i in U:
  print(i)
 
print(UA)
file.close() 

Number of users:50
{'uattrib2': '{2a}', 'uattrib3': '{3a}', 'uattrib4': '{4c}', 'uattrib7': '{7d}', 'uattrib8': '{8a}', 'uattrib9': '{9b}', 'uid': 'user1'}
{'uattrib0': '{0a}', 'uattrib1': '{1d}', 'uattrib2': '{2b}', 'uattrib3': '{3a}', 'uattrib6': '{6a}', 'uattrib8': '{8c}', 'uattrib9': '{9c}', 'uid': 'user2'}
{'uattrib1': '{1c}', 'uattrib2': '{2b}', 'uattrib4': '{4d}', 'uattrib5': '{5d}', 'uattrib6': '{6a}', 'uattrib7': '{7b}', 'uattrib8': '{8a}', 'uattrib9': '{9b}', 'uid': 'user3'}
{'uattrib1': '{1c}', 'uattrib5': '{5b}', 'uattrib6': '{6d}', 'uattrib7': '{7d}', 'uattrib9': '{9a}', 'uid': 'user4'}
{'uattrib0': '{0a}', 'uattrib1': '{1d}', 'uattrib2': '{2d}', 'uattrib3': '{3c}', 'uattrib4': '{4c}', 'uattrib5': '{5b}', 'uattrib6': '{6d}', 'uattrib7': '{7b}', 'uattrib8': '{8c}', 'uattrib9': '{9d}', 'uid': 'user5'}
{'uattrib1': '{1a}', 'uattrib3': '{3a}', 'uattrib6': '{6a}', 'uattrib7': '{7c}', 'uattrib8': '{8b}', 'uid': 'user6'}
{'uattrib0': '{0a}', 'uattrib1': '{1a}', 'uattrib3': '{3b}'

## Extract resources

In [28]:
#file = open(r'migration/8 8 10 10 10 1 1/OAR.txt' , 'r')
file = open(r'migration/50 50 10 10 50 1 4/OAR.txt' , 'r')
line = file.readline()
R=[] 
RA=[]
i=1     
while line: 
  r={}
  #print(line[:10])
  #print(line, end = '')　
  cons = line.strip().split(',')
  for con in cons:
    c = con.split('=')
    if(len(c)==2):
      r[c[0]]=c[1]
      if(c[0] not in RA):
        RA.append(c[0])

  r['rid']='resource'+str(i)
  i=i+1
  R.append(r)

  #break
  line = file.readline() 
print(f'Number of resources:{len(R)}')
for i in R:
  print(i)
 
print(RA)
file.close() 

Number of resources:50
{'rattrib0': '{0x}', 'rattrib2': '{2x}', 'rattrib3': '{3w}', 'rattrib4': '{4w}', 'rattrib6': '{6x}', 'rattrib7': '{7w}', 'rattrib8': '{8w}', 'rattrib9': '{9x}', 'rid': 'resource1'}
{'rattrib0': '{0z}', 'rattrib3': '{3w}', 'rattrib5': '{5y}', 'rattrib7': '{7w}', 'rattrib8': '{8w}', 'rattrib9': '{9w}', 'rid': 'resource2'}
{'rattrib1': '{1z}', 'rattrib4': '{4w}', 'rattrib5': '{5y}', 'rattrib6': '{6y}', 'rattrib7': '{7w}', 'rid': 'resource3'}
{'rattrib0': '{0y}', 'rattrib1': '{1z}', 'rattrib3': '{3y}', 'rattrib4': '{4y}', 'rattrib5': '{5x}', 'rattrib6': '{6y}', 'rattrib7': '{7x}', 'rattrib8': '{8y}', 'rattrib9': '{9y}', 'rid': 'resource4'}
{'rattrib0': '{0y}', 'rattrib2': '{2z}', 'rattrib3': '{3w}', 'rattrib4': '{4x}', 'rattrib5': '{5y}', 'rattrib6': '{6w}', 'rattrib7': '{7z}', 'rattrib8': '{8y}', 'rattrib9': '{9w}', 'rid': 'resource5'}
{'rattrib0': '{0y}', 'rattrib1': '{1z}', 'rattrib2': '{2w}', 'rattrib3': '{3x}', 'rattrib4': '{4w}', 'rattrib5': '{5w}', 'rattrib7':

## Define the ABAC policy

In [29]:
O=['access']
def dU(user,attribute):
  if attribute in user.keys():
    return user[attribute]

def dR(resource,attribute):
  if attribute in resource.keys():
    return resource[attribute]
ABAC_policy=(U,R,O,UA,RA,dU,dR,RU)

## Define the policy checker for ABAC rules

In [30]:
def satisfied(u,r,expressions):
  for expression in expressions:
    eu=expression['eu']
    er=expression['er']
    #for all the keys in eu get the constrina of this key
    #if u does not satisfy this const return false\
    if ( len(eu.keys()) != 0 and u != None):
      for key in eu.keys():
        if(dU(u,key)==None):
          return False
        for (op,c) in eu[key]:
        #op,c=eu[key]
        #print(op,c)
          if op == 'is' and dU(u,key) != c :
            return False

    #for all the keys in er get the constrinat of the key
    if ( len(er.keys()) != 0 and r != None):
      for key in er.keys():
        if (dR(r,key)==None):
          return False
        for (op,c) in er[key]:
        #print(op,c)
        #op,c=er[key]

          if op == 'is' and dR(r,key)!=c:

            return False
  
  return True


def check_ABAC_policy(request,abac_policy):
  u,r,o =request
  _,_,_,_,_,_,_,rules = abac_policy
  for rule in rules:
    if o in rule['operations']:
      if satisfied(u,r,rule['expressions'])==True:
        return True
  return False

# check the ABAC policy 
number_allow=0
number_deny=0
for u in U:
  for r in R:
    for o in O:
      if(check_ABAC_policy((u,r,o),ABAC_policy)==True):
        #print(u,'\n',r)
        number_allow= number_allow+1
      else:
        number_deny =number_deny +1 
        #print(f'{u}\n{r}\n{o}\n \n')

print(f'For ABAC policy:\nNumber of allowed requests:{number_allow}\nNumber of denied requests:{number_deny}')

#print(f'{check_ABAC_policy((U[6],R[7],"readMyScores"),ABAC_university)}\n{U[6]}\n{R[7]}')
#print(f'{check_ABAC_policy((U[3],R[5],"addScore"),ABAC_university)}\n{U[3]}\n{R[5]}')
#print(f'Loss at epo {epoch}: {losses/len(training_data)}')



For ABAC policy:
Number of allowed requests:169
Number of denied requests:2331


## Extrate user constraints and permissions

In [31]:
def get_item_id(item,list):
  id = 0
  while(id<len(list)):
    if item == list[id]:
      return id
    id = id + 1
  return None

from numpy import *
# Calculate the number of user constraints
# Calculate the number of conditional permissions(resource constraint,operation)
UC=[]
Permission=[]
Permission_set=[]
EU=[]
i=0
for rule in RU:
  user_cons=rule['expressions'][0]['eu']
  resource_cons=rule['expressions'][0]['er']
  operations=rule['operations']
  for uc_key in user_cons.keys():
    uc = {uc_key:user_cons[uc_key]}
    if uc not in UC:
      UC.append(uc)
  if (resource_cons,operations) not in Permission:
    Permission.append((resource_cons,operations))
########
  if user_cons not in EU:
    EU.append(user_cons)
    Permission_set.append([(resource_cons,operations)]) 
  elif user_cons in EU:
    if (resource_cons,operations) not in Permission_set[get_item_id(user_cons,EU)]:
      Permission_set[get_item_id(user_cons,EU)].append((resource_cons,operations)) 
      print(f'{get_item_id(user_cons,EU)}   {i}')

  i = i+1
print(f'permission_set:{len(Permission_set)}')
print(len(EU))

########
n_uc=len(UC)
n_p=len(Permission_set)
###n_p=len(Permission)
print(f'Number of user constraints:{n_uc}\nNumber of Permission:{n_p}')
print(UC)

###########
unique_pset=[]
for i in Permission_set:
  if i not in unique_pset:
    unique_pset.append(i)
print(len(unique_pset))
############

permission_set:50
50
Number of user constraints:40
Number of Permission:50
[{'uattrib3': [('is', '{3a}')]}, {'uattrib9': [('is', '{9b}')]}, {'uattrib4': [('is', '{4c}')]}, {'uattrib6': [('is', '{6a}')]}, {'uattrib1': [('is', '{1d}')]}, {'uattrib9': [('is', '{9c}')]}, {'uattrib8': [('is', '{8a}')]}, {'uattrib7': [('is', '{7b}')]}, {'uattrib4': [('is', '{4d}')]}, {'uattrib1': [('is', '{1c}')]}, {'uattrib5': [('is', '{5d}')]}, {'uattrib5': [('is', '{5b}')]}, {'uattrib6': [('is', '{6d}')]}, {'uattrib3': [('is', '{3c}')]}, {'uattrib2': [('is', '{2d}')]}, {'uattrib0': [('is', '{0a}')]}, {'uattrib8': [('is', '{8c}')]}, {'uattrib7': [('is', '{7c}')]}, {'uattrib8': [('is', '{8b}')]}, {'uattrib9': [('is', '{9d}')]}, {'uattrib4': [('is', '{4a}')]}, {'uattrib0': [('is', '{0c}')]}, {'uattrib8': [('is', '{8d}')]}, {'uattrib2': [('is', '{2c}')]}, {'uattrib3': [('is', '{3d}')]}, {'uattrib2': [('is', '{2b}')]}, {'uattrib6': [('is', '{6c}')]}, {'uattrib1': [('is', '{1b}')]}, {'uattrib0': [('is', '{0d}')

In [32]:
def cover(ma,mb):# ma cover mb
  if ma.shape[1] != mb.shape[1]:
    return False
  for i in range(ma.shape[1]):
    if mb[0,i]==1 and ma[0,i]==0:
      return False


  return True

## Extract permission-constraint and role-permission matrix

In [33]:
# permission-constraint matrix
pc=mat(zeros((n_p,n_uc)))
for rule in RU:
  user_cons=rule['expressions'][0]['eu']
  resource_cons=rule['expressions'][0]['er']
  operations=rule['operations']
  ####p_id=get_item_id((resource_cons,operations),Permission)
  p_id=get_item_id(user_cons,EU)
  for uc_key in user_cons.keys():
    uc = {uc_key:user_cons[uc_key]}
    c_id=get_item_id(uc,UC)
   #### if(c_id==None):
   ####   continue
    pc[p_id,c_id]=1
print(f'The pc matrix is\n {pc}')
####rp=mat(diag(array(ones(n_p))))
n_r = n_p
rp=mat(diag(array(ones(n_p))))



for i in range(n_r):
  for j in range(i+1,n_p):
    if (cover(pc[i,],pc[j,])):
      rp[i,j]=1
    if (cover(pc[j,],pc[i,])):
      rp[j,i]=1

print(f'The rp matrix is\n {rp}')

The pc matrix is
 [[1. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
The rp matrix is
 [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


## Calculate the user-role assignment and the role-permission assignment

In [34]:
def rest_of(l,r):
  vector = mat(zeros((1,n_p)))
  for role in l:
    if role != r:
      vector = vector + rp[role,]
  for i in range(n_p):
    if vector[0,i]>0:
      vector[0,i]=1
  return vector

Role_assigned =[]


import copy
# User role assignment 
n_r=n_p
rc=pc
URA = dict()

number_ura=0

print('The user-role assignment:')
for u in U:
  URA[u['uid']]=[]
  uv=mat(ones((1,n_uc)))
  for cid in range(n_uc):
    expressions=[{'eu':UC[cid],'er':{}}]
    if satisfied(u,None,expressions)==False:
      uv[0,cid]=0
  for rid in range(n_r):
    if cover(uv,rc[rid,]):
      URA[u['uid']].append(rid)

# remove hierarchy
  for ri in URA[u['uid']]:
    rest = URA[u['uid']].copy()
    rest.remove(ri)

    for rj in rest:
      if cover(rc[rj,],rc[ri,]) and ri in URA[u['uid']]:
        URA[u['uid']].remove(ri)
#remove redundant
  for r in URA[u['uid']]:
    if len(URA[u['uid']])==1:
      break
    if cover(rest_of(URA[u['uid']],r),rp[r,]) and r in URA[u['uid']]:
      URA[u['uid']].remove(r)

  ura =  URA[u['uid']]
  
  number_ura=number_ura+len(ura)
  print(f'User {get_item_id(u,U)+1}, role: {ura}')
  for r in ura:
    if (r not in Role_assigned):
      Role_assigned.append(r)
  #print(f'User {u}, role: {ura}')
#print(f'The user-role assignment:  {URA}')
 # print(f'The role-permission assignment:  {RPA}')

# generate the role-heirarchy
RH = []
for i in range(0,n_r-1):
  for j in range(i+1,n_r):
    if (cover(pc[i,],pc[j,])):
      RH.append((i,j))
    if (cover(pc[j,],pc[i,])):
      RH.append((j,i))    
print(f'\n\nThe role-hierarchy relationship:  {RH}')
# generate the role-permission assignment
RPA = dict()

for ro in range(n_r):
  RPA['role'+str(ro)]=[]

################3
for pid in range(n_p):
  for o in O:
    for r in R:
      for role_id in range(n_r):
        if rp[role_id,pid]==1:
           #(er,operations) = Permission[pid]
           for (er,operations) in Permission_set[pid]:
             expressions=[{'eu':{},'er':er}]
             if satisfied(None,r,expressions) and o in operations:
               if ((r,o) not in RPA['role'+str(role_id)]):
                 RPA['role'+str(role_id)].append((r,o))
##################
 # for r in R:
  #  for o in O:
   #   for pid in range(n_p):
  #      if rp[ro,pid]==1:
          ########
  #        for (er,operations) in Permission_set[pid]:
          #print(er,r)
  #          expressions=[{'eu':{},'er':er}]
            #print(satisfied(None,r,expressions))
   #         if satisfied(None,r,expressions) and o in operations:
   #           if((r,o) not in RPA['role'+str(ro)]):
   #             RPA['role'+str(ro)].append((r,o))

print('\n\nThe role-permission assignment:')

number_rpa=0
for ro in range(n_r):
  p=RPA['role'+str(ro)]
  number_rpa=number_rpa+len(p)
  print(f'Role：{ro}, Number of permissions:{len(p)},  Permissions: {p}')

#print(f'Number of different roles is ：{len(unique_pset)}')
#if len(unique_pset)<n_r:
#  print('Some roles in the role-permission assignment are the same.')

print(f'The number of user-role assignment:  {number_ura}')

print(f'The number of role-permission assignment:  {number_rpa}')
print(f'The number of roles assigned:  {len(Role_assigned)}: {Role_assigned}')

The user-role assignment:
User 1, role: [0]
User 2, role: [1]
User 3, role: [2]
User 4, role: [3, 24]
User 5, role: [4]
User 6, role: [5]
User 7, role: [6]
User 8, role: [7]
User 9, role: [8]
User 10, role: [9]
User 11, role: [10]
User 12, role: [33]
User 13, role: [12]
User 14, role: [12, 13]
User 15, role: [14]
User 16, role: [15]
User 17, role: [26]
User 18, role: [17]
User 19, role: [3, 5, 18]
User 20, role: [19, 26]
User 21, role: [20]
User 22, role: [30]
User 23, role: [22]
User 24, role: [23]
User 25, role: [24]
User 26, role: [25]
User 27, role: [26]
User 28, role: [27]
User 29, role: [28]
User 30, role: [29]
User 31, role: [30]
User 32, role: [31]
User 33, role: [32]
User 34, role: [33]
User 35, role: [34]
User 36, role: [35]
User 37, role: [36]
User 38, role: [37]
User 39, role: [38]
User 40, role: [39]
User 41, role: []
User 42, role: []
User 43, role: []
User 44, role: []
User 45, role: []
User 46, role: []
User 47, role: []
User 48, role: []
User 49, role: []
User 50, role

In [15]:
# check RBAC policy
#def check_RBAC_policy(request,rp,URA):
#  u,r,o =request
#  for role_id in URA[u['uid']]:
#    for pid in range(n_p):
#      if rp[role_id,pid]==1:
#        (er,operations) = Permission[pid]
#        expressions=[{'eu':{},'er':er}]
#        if satisfied(u,r,expressions) and o in operations:
#          return True
######
# check RBAC policy
def check_RBAC_policy(request,RPA,URA):
  u,r,o =request
  for role_id in URA[u['uid']]:
    if (r,o) in RPA['role'+str(role_id)]:
      return True

  return False
# Check the RBAC
# check the RBAC policy 

number_allow=0
number_deny=0
for u in U:
  for r in R:
    for o in O:
      if (check_RBAC_policy((u,r,o),RPA,URA)==True):
        number_allow= number_allow+1
      else:
        number_deny =number_deny +1 
        #print(f'{u}\n{r}\n{o}\n \n')

print(f'For RBAC:\nNumber of allowed requests:{number_allow}\nNumber of denied request:{number_deny}')

For RBAC:
Number of allowed requests:48
Number of denied request:16


In [16]:

# check the RBAC policy 
number_allow=0
number_deny=0
for u in U:
  for r in R:
    for o in O:
      if(check_RBAC_policy((u,r,o),RPA,URA)==True):
        number_allow= number_allow+1
      else:
        number_deny =number_deny +1 
        #print(f'{u}\n{r}\n{o}\n \n')
print(f'For RBAC:\nNumber of allowed requests:{number_allow}\nNumber of denied request:{number_deny}')

# check the ABAC policy 
number_allow=0
number_deny=0
m= []
for u in U:
  l = []
  for r in R:
    for o in O:
      if(check_ABAC_policy((u,r,o),ABAC_policy)==True):
        l.append(1)
        number_allow= number_allow+1
      else:
        number_deny =number_deny +1 
        l.append(0)
        #print(f'{u}\n{r}\n{o}\n \n')
  m.append(l)

print(f'For ABAC:\nNumber of allowed requests:{number_allow}\nNumber of denied request:{number_deny}')
#for i in m:
#  print(i)
#number_allow=0
#number_deny=0

correct=0
for u in U:
 
  for r in R:
    for o in O:
      if (check_ABAC_policy((u,r,o),ABAC_policy)==True and check_RBAC_policy((u,r,o),RPA,URA)==False):
        print(f'TF{u} {r} {o}')
      elif (check_ABAC_policy((u,r,o),ABAC_policy)==False and check_RBAC_policy((u,r,o),RPA,URA)==True):
        print(f'FT{u} {r} {o}')
        #number_allow= number_allow+1
      elif (check_ABAC_policy((u,r,o),ABAC_policy)==True and check_RBAC_policy((u,r,o),RPA,URA)==True):
        correct = correct +1
      elif (check_ABAC_policy((u,r,o),ABAC_policy)==False and check_RBAC_policy((u,r,o),RPA,URA)==False):
        correct = correct +1
        #number_deny =number_deny +1 
        #print(f'{u}\n{r}\n{o}\n \n')

print(f'For number of correct:{correct}')


For RBAC:
Number of allowed requests:48
Number of denied request:16
For ABAC:
Number of allowed requests:48
Number of denied request:16
For number of correct:64
